"""
agent-backend.app.agents.escalation
--------------------------------------
Escalation Agent — invoked directly (not part of the Graph) when Maria
taps "Help me" (architecture.md §7.6).

Fail-open design (architecture.md §7.6):
    The Escalation Agent has a 3-second hard timeout. If it fails or times
    out for any reason, the alert is STILL created by application code using
    Maria's raw note (or a generic default). The agent's only job is to make
    the alert more informative — the alert's existence never depends on the
    agent succeeding.

    Both paths (agent success and fallback) call mcp.create_help_alert() in
    the FastAPI router. This function only produces the category + summary
    strings; it never writes to the database.
"""

import asyncio
import logging
import re
from dataclasses import dataclass

from strands import Agent
from strands.models.bedrock import BedrockModel

from ..config import AWS_REGION, BEDROCK_MODEL_ID_FAST
from .prompts import ESCALATION_SYSTEM_PROMPT

logger = logging.getLogger(__name__)

# Hard timeout per architecture.md §7.6
ESCALATION_TIMEOUT_SECONDS: float = 3.0

# Fallback values used when the agent times out or errors
FALLBACK_CATEGORY: str = "help_requested"


@dataclass
class EscalationResult:
    """
    Result from invoke_escalation_agent().

    Attributes:
        category:        Short category label (e.g. "feeling_unwell").
        summary:         One-sentence calm summary for the caregiver.
        from_fallback:   True if the agent timed out or errored and the
                         values were generated by the deterministic fallback.
    """
    category: str
    summary: str
    from_fallback: bool = False


# ---------------------------------------------------------------------------
# Output parser
# ---------------------------------------------------------------------------
_CATEGORY_RE = re.compile(r"^CATEGORY:\s*(.+)$", re.MULTILINE | re.IGNORECASE)
_SUMMARY_RE = re.compile(r"^SUMMARY:\s*(.+)$", re.MULTILINE | re.IGNORECASE)


def _parse_escalation_output(text: str) -> tuple[str, str] | None:
    """
    Parse the Escalation Agent's response into (category, summary).

    Returns None if the required markers are not found — the caller then
    uses the deterministic fallback values.
    """
    category_match = _CATEGORY_RE.search(text)
    summary_match = _SUMMARY_RE.search(text)
    if category_match and summary_match:
        return (
            category_match.group(1).strip()[:50],   # cap length for DB
            summary_match.group(1).strip()[:500],   # cap length for DB
        )
    return None


# ---------------------------------------------------------------------------
# Agent construction — once per process, reused across requests
# ---------------------------------------------------------------------------
_escalation_agent: Agent | None = None


def _get_escalation_agent() -> Agent:
    """Return the Escalation Agent singleton (constructed once at first call)."""
    global _escalation_agent
    if _escalation_agent is None:
        _escalation_agent = Agent(
            name="escalation",
            system_prompt=ESCALATION_SYSTEM_PROMPT,
            tools=[],           # no tools — ADR-002
            model=BedrockModel(
                model_id=BEDROCK_MODEL_ID_FAST,
                region_name=AWS_REGION,
                temperature=0.2,
            ),
        )
    return _escalation_agent


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
async def invoke_escalation_agent(
    note: str | None,
    routine_title: str | None = None,
) -> EscalationResult:
    """
    Invoke the Escalation Agent with a 3-second hard timeout.

    If the agent responds in time and produces parseable output, returns
    an EscalationResult with from_fallback=False.

    If the agent times out, raises an exception, or returns unparseable
    output, returns a deterministic fallback EscalationResult with
    from_fallback=True so the caller can log which path was taken.

    Args:
        note:           Maria's optional free-text note.
        routine_title:  The routine she was on when she tapped Help me,
                        for context in the agent prompt.

    Returns:
        EscalationResult — always returns (never raises), by design.
    """
    agent = _get_escalation_agent()

    # Build the input message
    parts = []
    if routine_title:
        parts.append(f"The assisted user was on the routine: {routine_title!r}.")
    if note:
        parts.append(f"Their note: {note!r}")
    else:
        parts.append("No note was provided.")
    input_text = " ".join(parts)

    try:
        # Run the synchronous Strands Agent call in a thread executor so it
        # doesn't block the FastAPI event loop, with a hard 3-second timeout.
        loop = asyncio.get_event_loop()
        result = await asyncio.wait_for(
            loop.run_in_executor(None, lambda: agent(input_text)),
            timeout=ESCALATION_TIMEOUT_SECONDS,
        )
        output_text = str(result)
        parsed = _parse_escalation_output(output_text)

        if parsed:
            category, summary = parsed
            logger.info(
                "Escalation Agent succeeded: category=%s", category
            )
            return EscalationResult(category=category, summary=summary)
        else:
            logger.warning(
                "Escalation Agent returned unparseable output — using fallback. "
                "Output snippet: %.200s", output_text
            )
            return _make_fallback(note)

    except asyncio.TimeoutError:
        logger.warning(
            "Escalation Agent timed out after %.1fs — using fallback.",
            ESCALATION_TIMEOUT_SECONDS,
        )
        return _make_fallback(note)
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "Escalation Agent raised an exception — using fallback. %s", exc
        )
        return _make_fallback(note)


def _make_fallback(note: str | None) -> EscalationResult:
    """Build the deterministic fallback EscalationResult."""
    summary = (
        note.strip()[:500]
        if note and note.strip()
        else "The assisted user requested help without providing further detail."
    )
    return EscalationResult(
        category=FALLBACK_CATEGORY,
        summary=summary,
        from_fallback=True,
    )
